### ISSUE TITLE
Days cannot be correctly closed with lstosa v0.10.8

### ISSUE THREAD

**Issue by marialainez** [cta-observatory/lstosa#276]
With version 0.10.8 of lstosa, autocloser gives the following error: 

```
 File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/osa/scripts/closer.py", line 159, in post_process
    longterm_job_id = daily_datacheck(daily_longterm_cmd(list_job_id))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/osa/scripts/closer.py", line 492, in daily_datacheck
    job_id = job.stdout.strip()
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

2024-02-07 17:02:01,791 WARNING [root] (autocloser.main): Could not close the day for LST1!
```

For this reason, the DL1 files are not merged (as DL1 merging is done afterward) and the day is not closed correctly.

**Comment by morcuended** [comment]
The problem is that `daily_longterm` is running the subprocess simply as `.run(cmd, check=True)` and the stdout is not being captured, hence the error in `job_id = job.stdout.strip()`

https://github.com/cta-observatory/lstosa/blob/490b902011edde355e109ffff9187803f14b677a/src/osa/scripts/closer.py#L491

should be instead:

```python
    job = subprocess.run(
        cmd,
        encoding="utf-8",
        capture_output=True,
        text=True,
        check=True,
    )
```
So the stdout of the job output is captured.
